### ISSUE TITLE
NPE in SystemMonitor metrics dump

### ISSUE THREAD

**Issue by ar** [jpos/jPOS#189]
```
java.lang.NullPointerException
        at org.jpos.q2.qbean.SystemMonitor.lambda$dumpMetrics$0(SystemMonitor.java:271)
        at java.util.HashMap.forEach(HashMap.java:1289)
        at org.jpos.q2.qbean.SystemMonitor.dumpMetrics(SystemMonitor.java:268)
        at org.jpos.q2.qbean.SystemMonitor.dump(SystemMonitor.java:134)
        at org.jpos.util.LogEvent.dump(LogEvent.java:139)
        at org.jpos.util.SimpleLogListener.log(SimpleLogListener.java:51)
        at org.jpos.util.Logger.log(Logger.java:99)
        at org.jpos.util.Log.info(Log.java:81)
        at org.jpos.q2.qbean.SystemMonitor.run(SystemMonitor.java:128)
        at java.lang.Thread.run(Thread.java:748)
```

how to reproduce?
change `<property name="debug" value="true"/>` to `<property name="debug" value="flase"/>` in 30_txnmgr.xml from jpos-gateway.pdf

how to fix?
change `<property name="metrics-dir" value="log" />` to `<!--<property name="metrics-dir" value="log" />-->` in 99_sysmon.xml

Reported by Igor.

**Comment by it240884sii** [comment]
`public Metrics getMetrics() {
        return metrics;
    }`
in TransactionManager return null because metrics instantiated ONLY `if (profiler)` in `setConfiguration` return true.
