### ISSUE TITLE
Context.dumpMap is throwing ConcurrentModificationException

### ISSUE THREAD

**Issue by ar** [jpos/jPOS#212]
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:711)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:744)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:742)
	at org.jpos.transaction.Context.dumpMap(Context.java:250)
	at org.jpos.transaction.Context.dump(Context.java:147)
	at org.jpos.util.LogEvent.dump(LogEvent.java:139)
	at org.jpos.util.LogEvent.toString(LogEvent.java:219)
	at org.jpos.util.LogEvent.toString(LogEvent.java:224)
	at org.jpos.util.FrozenLogEvent.<init>(FrozenLogEvent.java:28)
	at org.jpos.transaction.TransactionManager.run(TransactionManager.java:397)
	at java.lang.Thread.run(Thread.java:745)
```

[jPOS-Users discussion](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jpos-users/UeXSYflEZ_I/QWyQf0NfCgAJ)

**Comment by chhil** [comment]
If the map is a Collections.synchronizedMap (new LinkedHashMap<>()); do we still need to use synchronized while iterating it?

**Comment by ar** [comment]
Yes. From `Collections.synchronizedMap` javadoc:

> It is imperative that the user manually synchronize on the returned
> map when iterating over any of its collection views:
