### ISSUE TITLE
DB - Detected concurrent management of connection resources.

### ISSUE THREAD

**Issue by ar** [jpos/jPOS#383]
From PR197

```
org.jpos.gl.AccountLockTest > executionError FAILED
    org.hibernate.HibernateException: Detected concurrent management of connection resources. This might indicate a multi-threaded use of Hibernate in combination with managed resources, which is not supported.
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.releaseConnection(LogicalConnectionManagedImpl.java:221)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.close(LogicalConnectionManagedImpl.java:258)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.close(JdbcCoordinatorImpl.java:175)
        at org.hibernate.internal.AbstractSharedSessionContract.close(AbstractSharedSessionContract.java:342)
        at org.hibernate.internal.SessionImpl.closeWithoutOpenChecks(SessionImpl.java:385)
        at org.hibernate.internal.SessionImpl.close(SessionImpl.java:361)
        at org.jpos.ee.DB.close(DB.java:330)
        at org.jpos.gl.GLSession.close(GLSession.java:1520)
        at org.jpos.gl.TestBase.tearDownBase(TestBase.java:100)
```

https://github.com/jpos/jPOS-EE/pull/197#issuecomment-743710576

**Comment by ar** [comment]
Probable reference: https://hibernate.atlassian.net/browse/HHH-14143
