### ISSUE TITLE
Running Q2 embedded with wrong SAX driver

### ISSUE THREAD

**Issue by yazalulloa** [jpos/jPOS#409]
I'm trying to run Q2 inside a Dropwizard application and I'm finding some errors when deploying.

This is the log that shows the error with every configuration file

```xml
<log realm="Q2.system" at="2021-04-18T14:56:57.871484800">
  <warn>
    Tidying C:\project\deploy\00_logger.xml out of the way, by adding .BAD
    It will be called: C:\project\deploy\00_logger.xml.BAD see log above for detail of problem.
  </warn>
</log>
<log realm="Q2.system" at="2021-04-18T14:56:57.873483100" lifespan="215673ms">
  <info>
    <exception name="http://apache.org/xml/features/xinclude feature not recognized for SAX driver oracle.xml.parser.v2.SAXParser">
    org.jdom2.JDOMException: http://apache.org/xml/features/xinclude feature not recognized for SAX driver oracle.xml.parser.v2.SAXParser
	at org.jdom2.input.SAXBuilder.internalSetFeature(SAXBuilder.java:1025)
	at org.jdom2.input.SAXBuilder.configureParser(SAXBuilder.java:976)
	at org.jdom2.input.SAXBuilder.buildEngine(SAXBuilder.java:856)
	at org.jdom2.input.SAXBuilder.getEngine(SAXBuilder.java:904)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1116)
	at org.jpos.q2.Q2.deploy(Q2.java:572)
	at org.jpos.q2.Q2.deploy(Q2.java:401)
	at org.jpos.q2.Q2.run(Q2.java:267)
	at java.base/java.lang.Thread.run(Thread.java:834)
    </exception>
  </info>
</log>
<log realm="Q2.system" at="2021-04-18T14:56:57.878485">
  <info>
    removed deploy/00_logger.xml
    created deploy/00_logger.xml.BAD
  </info>
</log>
```

After I debugged the deployment I found out that the org.xml.sax.XmlReader that was being created in org.jdom2.input.SAXBuilder in the method createParser() was oracle.xml.parser.v2.SAXParser, this application has a connection to an oracle database so I cannot remove that, is there any way to set a functioning XmlReader?

This is one of the files I put in the deploy folder:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<logger name="Q2" class="org.jpos.q2.qbean.LoggerAdaptor">
  <log-listener class="org.jpos.util.SimpleLogListener" />
  <log-listener class="org.jpos.util.BufferedLogListener">
    <property name="max-size" value="100" />
    <property name="name" value="logger.Q2.buffered" />
  </log-listener>

  <!--
  <log-listener class="org.jpos.util.SysLogListener">
     <property name="facility" value="21" />
     <property name="severity" value="5" />
     <property name="tags" value="audit, syslog" />
     <property name="prefix" value="[jPOS]" />
  </log-listener>
  -->

  <log-listener class="org.jpos.util.DailyLogListener">
    <property name="window" value="86400" /> <!-- optional, default one day -->
    <!--needed-->
    <property name="prefix" value="log/q2" />
    <property name="suffix" value=".log"/> <!-- optional -->

    <!--optional the default is "-yyyy-MM-dd" -->
    <property name="date-format" value="-yyyy-MM-dd-HH"/>

    <!--optional the default is gzip-->
    <property name="compression-format" value="gzip"/> 

    <!--optional the default is .zip for zip, .gz for gzip-->
    <!--
    <property name="compressed-suffix" value=".zip"/>
    -->
    <!--
      almost equals to rotate, except 0 or negatives means no limit 
     (which is the default), in case exceeded the file is compressed, 
     successsive copies will be appended .(count) before the suffix
     unlike rotate older copies have the least numbers
    -->
    <!-- <property name="maxsize" value="-1"/> -->

    <!-- 
      this is a low level parameter which determines the size of the 
      buffer used to read from the uncompressed file, the default is 
      128*1024 = 128 KB, use bigger values in machines with lot of
      memory and your logs are big
    -->
    <!--
    <property name="compression-buffer-size" value="131072"/>
    -->
    <!--
     first-rotate-time and first-rotate-date determines the first rotation, 
     succesive rotations will take place at the time determined by this two 
     parameters plus multiples of window, the defaults are 00:00:00 and today 
     and the formats are HH:mm:ss and yyyy-MM-dd respectively
    -->
  </log-listener>
</logger>
```

**Comment by ar** [comment]
Looks like a question for the jdom2 list. Perhaps you can tweak `org.xml.sax.driver` property. If you find that there's anything we can do from the jPOS side to simplify that, just let us know.

**Comment by yazalulloa** [comment]
The org.xml.sax.driver system property was the solution, thank you
